{
 "title": "Computer Vision - Cats & Dogs (Workshop)",
 "tags": [
  "mlops",
  "computer-vision",
  "workshop"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "🗄️ Statut Base de Données",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cv_database_connected" }
   ]
  },
  {
   "title": "Nombre de requêtes moyen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!~\"/metrics|/health|none\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requêtes (par endpoint)",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{handler!~\"/metrics|/health|none\"}[5m])) by (handler)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temps d'inférence (s)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(cv_inference_time_seconds_sum[5m]) / rate(cv_inference_time_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Répartition des feedbacks sur la période sélectionnée",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "increase(cv_user_feedback_total{feedback=\"0\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(cv_user_feedback_total{feedback=\"1\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taux de prédiction (confiance < 60%)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(cv_prediction_confidence_bucket{le=\"60.0\"}[1h]))/sum(rate(cv_prediction_confidence_count[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution des cibles",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cv_predicted_target_total{target=\"dog\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "increase(cv_predicted_target_total{target=\"cat\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "📊 Dernières Prédictions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT created_at, prediction_result, ROUND(proba_cat::numeric, 2) as proba_cat, ROUND(proba_dog::numeric, 2) as proba_dog FROM predictions_feedback ORDER BY created_at DESC LIMIT 10"
    }
   ]
  }
 ]
}